# A Gemini rules file for a Scrapy-based Python repository.
# Policy: default include of source/config/docs; explicitly ignore caches, local env,
# build artifacts, outputs, and runtime/stateful directories. Keep core code, tests,
# infra, and docs in scope so the agent can reason and ship safely.

rules:
  # === VCS, build outputs, Python packaging ===
  - pattern: ".git/"
    action: ignore
  - pattern: ".github/"
    action: ignore
  - pattern: "dist/"
    action: ignore
  - pattern: "build/"
    action: ignore
  - pattern: "*.egg-info/"
    action: ignore
  - pattern: ".eggs/"
    action: ignore

  # === Python caches & virtual envs ===
  - pattern: ".venv/"
    action: ignore
  - pattern: "venv/"
    action: ignore
  - pattern: "__pycache__/**"
    action: ignore
  - pattern: ".pytest_cache/"
    action: ignore
  - pattern: ".mypy_cache/"
    action: ignore
  - pattern: ".ruff_cache/"
    action: ignore
  - pattern: ".tox/"
    action: ignore
  - pattern: ".nox/"
    action: ignore

  # === Scrapy / crawler state & runtime outputs ===
  - pattern: ".scrapy/"
    action: ignore          # HTTP cache, local crawl state
  - pattern: "data/out/**"
    action: ignore          # CSV and run artifacts written by FEEDS
  - pattern: "scrapyd/logs/**"
    action: ignore
  - pattern: "scrapyd/eggs/**"
    action: ignore
  - pattern: "scrapyd/dbs/**"
    action: ignore

  # === Playwright runtime artifacts (if enabled) ===
  - pattern: "ms-playwright/**"
    action: ignore
  - pattern: "playwright-report/**"
    action: ignore

  # === OS / editor cruft ===
  - pattern: ".DS_Store"
    action: ignore
  - pattern: "Thumbs.db"
    action: ignore
  - pattern: ".idea/"
    action: ignore
  - pattern: ".vscode/"
    action: ignore
  - pattern: ".devcontainer/"
    action: ignore
  - pattern: ".ipynb_checkpoints/"
    action: ignore

  # === Logs, coverage, reports ===
  - pattern: "*.log"
    action: ignore
  - pattern: "logs/**"
    action: ignore
  - pattern: "coverage/**"
    action: ignore
  - pattern: ".coverage*"
    action: ignore
  - pattern: "htmlcov/**"
    action: ignore
  - pattern: "test-results/**"
    action: ignore

  # === Env & local overrides (never ingest secrets) ===
  - pattern: ".env"
    action: ignore
  - pattern: ".env.*"
    action: ignore
  - pattern: ".envrc"
    action: ignore
  - pattern: ".docker.env"
    action: ignore

  # === Explicit includes: core source, config, infra ===
  - pattern: "src/**/*.py"
    action: include
  - pattern: "src/**/py.typed"
    action: include
  - pattern: "scrapy.cfg"
    action: include
  - pattern: "manifests/**/*.{yml,yaml,json}"
    action: include

  # Scrapy project package (if you keep a fixed name)
  - pattern: "src/project/**"
    action: include
  - pattern: "src/app/**"
    action: include
  - pattern: "src/selector_tools/**"
    action: include

  # Infra & deployment
  - pattern: "infra/**"
    action: include
  - pattern: "Dockerfile"
    action: include
  - pattern: "docker-compose*.yml"
    action: include
  - pattern: ".dockerignore"
    action: include
  - pattern: "prometheus.yml"
    action: include
  - pattern: "grafana/**"
    action: include
  - pattern: "scrapyd.conf"
    action: include

  # Python/tooling configs
  - pattern: "pyproject.toml"
    action: include
  - pattern: "requirements*.txt"
    action: include
  - pattern: "constraints*.txt"
    action: include
  - pattern: "uv.lock*"
    action: include
  - pattern: "poetry.lock"
    action: include
  - pattern: "setup.cfg"
    action: include
  - pattern: "mypy.ini"
    action: include
  - pattern: "ruff.toml"
    action: include
  - pattern: "pytest.ini"
    action: include
  - pattern: ".pre-commit-config.yaml"
    action: include
  - pattern: ".flake8"
    action: include

  # Tests, fixtures, docs
  - pattern: "tests/**"
    action: include
  - pattern: "docs/**"
    action: include
  - pattern: "**/*.md"
    action: include
  - pattern: "GEMINI.md"
    action: include
  - pattern: ".gemini.yaml"
    action: include

  # Sample data and fixtures (explicitly included; adjust as needed)
  - pattern: "tests/fixtures/**/*.html"
    action: include
  - pattern: "tests/fixtures/**/*.json"
    action: include
  - pattern: "tests/fixtures/**/*.csv"
    action: include

  # Optional: include manifests or job specs outside /manifests
  - pattern: "**/*jobs*.{yml,yaml,json}"
    action: include
